apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: registry-intl.cn-shanghai.aliyuncs.com/coollog/frontend-service
    jibGradle: {}
    context: frontend-service
  - image: registry-intl.cn-shanghai.aliyuncs.com/coollog/vote-service
    jibGradle: {}
    context: vote-service
  - image: registry-intl.cn-shanghai.aliyuncs.com/coollog/notification-service
    context: notification-service
