apiVersion: skaffold/v1beta4
kind: Config
build:
  artifacts:
  - image: gcr.io/qingyangc-sandbox/frontend-service
    jibGradle: {}
    context: frontend-service
  - image: gcr.io/qingyangc-sandbox/vote-service
    jibGradle: {}
    context: vote-service
  - image: gcr.io/qingyangc-sandbox/notification-service
    context: notification-service
